/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC5
 * Generated at: 2014-07-09 15:04:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import example.SqlOperation;
import org.kohsuke.github.GHMyself;
import org.kohsuke.github.GitHub;
import net.minidev.json.JSONObject;
import net.minidev.json.JSONArray;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


HttpSession session2 = request.getSession();
String access_token = (String)session2.getAttribute("access_token");


JSONObject u_info = new JSONObject();
JSONArray commitrecord = new JSONArray();

if(access_token == null){
	   u_info.put("access", false);
} else{
	   u_info.put("access", true);
	   GitHub github = GitHub.connectUsingOAuth(access_token);
	   GHMyself myself = github.getMyself();
	   u_info.put("user", myself.getLogin());
	   u_info.put("email", myself.getEmail());
	   u_info.put("id", myself.getId());
	   u_info.put("name", myself.getName());
	   
	   SqlOperation sqlo = new SqlOperation();
	   // get user edit history here...
	   commitrecord = sqlo.SelectCommit(myself.getId());
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>Github Edit System</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"./css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./css/dashboard.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \tvar user = ");
      out.print( u_info.toString() );
      out.write(";\r\n");
      out.write("    \tvar record = ");
      out.print( commitrecord.toString() );
      out.write(";\r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"#\">GitHub Edit System</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t<li><a href=\"http://localhost:8080/HelloWorld/path.html\">Back to DIR</a></li>\r\n");
      out.write("            <li><a href=\"#\">Help</a></li>\r\n");
      out.write("            <li id=\"log_out\"><a href=\"#\">Logout</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-sm-9 col-md-10 main\">\r\n");
      out.write("          <h1 class=\"page-header\">Edit Record</h1>\r\n");
      out.write("          <div class=\"table-responsive\">\r\n");
      out.write("            <table id=\"recordtable\" class=\"table table-striped\">\r\n");
      out.write("              <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th>FileName</th>\r\n");
      out.write("                  <th>CommitCode</th>\r\n");
      out.write("                  <th>EditTime</th>\r\n");
      out.write("                  <th>FileLink</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </thead>\r\n");
      out.write("              <tbody>\r\n");
      out.write("\r\n");
      out.write("              </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("\t\t  <img data-src=\"holder.js/200x200/auto/sky\" class=\"img-circle\" alt=\"200x200\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgZmlsbD0iIzBEOEZEQiIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjEwMCIgeT0iMTAwIiBzdHlsZT0iZmlsbDojZmZmO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1zaXplOjEzcHg7Zm9udC1mYW1pbHk6QXJpYWwsSGVsdmV0aWNhLHNhbnMtc2VyaWY7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+MjAweDIwMDwvdGV4dD48L3N2Zz4=\">\r\n");
      out.write("          <ul class=\"nav nav-sidebar\">\r\n");
      out.write("            <li><a href=\"#\">NAME:<span id=\"user_login\"></span></a></li>\r\n");
      out.write("            <li><a href=\"#\">ID:<span id=\"user_id\"></span></a></li>\r\n");
      out.write("            <li><a href=\"#\">email:<span id=\"user_email\"></span></a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"navbar navbar-default navbar-fixed-bottom\" role=\"navigation\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-collapse collapse\">\r\n");
      out.write("\t\t  <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li>This is FootNote!</li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("    <!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"../../dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"../../assets/js/docs.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(function(){\r\n");
      out.write("    \t$(\"#log_out\").click(function(){\r\n");
      out.write("\t\t\t\t$.get(\"./logout\", null, null, \"json\")\r\n");
      out.write("\t\t\t .success(function(resp){\r\n");
      out.write("\t\t\t\tif(resp.status = true){\r\n");
      out.write("\t\t\t\t\talert(\"Log out success!\");\r\n");
      out.write("\t\t\t\t\twindow.location.href = \"http://localhost:8080/HelloWorld/git_index.html\";\r\n");
      out.write("\t\t\t \t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("    \t\r\n");
      out.write("    \t$(\"#user_id\").text(user[\"id\"]);\r\n");
      out.write("    \t$(\"#user_login\").text(user[\"user\"]);\r\n");
      out.write("    \t$(\"#user_email\").text(user[\"email\"]);\r\n");
      out.write("\t\t// insert record\r\n");
      out.write("\t\tvar tableRf;\r\n");
      out.write("\t\tvar rows;\r\n");
      out.write("\t\tvar row;\r\n");
      out.write("\t\tvar fname, ccode, ctime, link;\r\n");
      out.write("\t\tvar cell;\r\n");
      out.write("\t\tfor(i = 0; i < record.length; i++){\r\n");
      out.write("\t\t\tdt = record[i];\r\n");
      out.write("\t\t\tfname = dt.filename;\r\n");
      out.write("\t\t\tccode = dt.commitcode;\r\n");
      out.write("\t\t\tctime = dt.created_time;\r\n");
      out.write("\t\t\tlink = dt.filelink;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\ttableRf = document.getElementById('recordtable');\r\n");
      out.write("\t\t\trows = tableRf.getElementsByTagName('tbody')[0].getElementsByTagName('tr').length;\r\n");
      out.write("\t\t\trow = tableRf.insertRow(rows+1);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcell = row.insertCell(0);\r\n");
      out.write("\t\t\tcell.innerHTML = fname;\r\n");
      out.write("\t\t\tcell = row.insertCell(1);\r\n");
      out.write("\t\t\tcell.innerHTML = ccode;\r\n");
      out.write("\t\t\tcell = row.insertCell(2);\r\n");
      out.write("\t\t\tcell.innerHTML = ctime;\r\n");
      out.write("\t\t\tcell = row.insertCell(3);\r\n");
      out.write("\t\t\tcell.innerHTML = \"<a href=\\\"\" + link + \"\\\">\" + link + \"</a>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
